import Head from "next/head";
import { Header } from "./Header";
import { Footer } from "./Footer";

export const Layout = ({ children, header, footer }) => {
  return (
    <>
      <Head>
        <title>Rae Barnes Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header items={header} />
      <main>{children}</main>
      <Footer items={footer} />
    </>
  );
};
